image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - docker-compose up
  - sleep 10
  - java -Dspring.datasource.url=jdbc:postgresql://localhost:5432/app -jar artifacts/aqa-shop.jar &
  - sleep 10

build_script:

  - chmod +x gradlew
  - ./gradlew clean test -Ddb.url=jdbc:postgresql://localhost:5432/app -Dselenide.headless=true --info
